[doc]
name = "Binary Liquid-Vapor Phase Diagram"
bundle = "https://data1.fullyjustified.net/tlextras-2022.0r0.tar"

[[output]]
name = "binary_phases"
type = "pdf"
shell_escape = true
shell_escape_cwd = ".."
